import base64
import json
import urllib.request
import urllib.error
import time
import os
import subprocess
from typing import Dict, Any, Optional
from .llm_openapi import LLMOpenAPIConverter

class GithubRemediator:
    """
    Manages automated PR remediation logic by updating a target LOM prompt spec
    file on a new branch in a GitHub repository and opening a Pull Request.
    """
    def __init__(self, repo: str, token: str, target_file: str, base_branch: str = "main"):
        self.repo = repo  # format: "owner/repo"
        self.token = token
        self.target_file = target_file.lstrip("/")
        self.base_branch = base_branch
        self.base_url = f"https://api.github.com/repos/{repo}"

    def _headers(self) -> Dict[str, str]:
        return {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "LOD-Gateway-Remediator/0.1.0"
        }

    def _request(self, path: str, method: str = "GET", data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        url = f"{self.base_url}/{path}"
        req_data = None
        if data is not None:
            req_data = json.dumps(data).encode("utf-8")
        
        req = urllib.request.Request(url, data=req_data, headers=self._headers(), method=method)
        try:
            with urllib.request.urlopen(req, timeout=15) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            err_content = e.read().decode("utf-8")
            try:
                err_json = json.loads(err_content)
                msg = err_json.get("message", err_content)
            except Exception:
                msg = err_content
            raise ValueError(f"GitHub API Error ({e.code}): {msg}")
        except Exception as e:
            raise ValueError(f"Failed to communicate with GitHub API: {e}")

    def get_base_sha(self) -> str:
        res = self._request(f"git/ref/heads/{self.base_branch}")
        return res["object"]["sha"]

    def create_branch(self, branch_name: str, base_sha: str) -> None:
        data = {
            "ref": f"refs/heads/{branch_name}",
            "sha": base_sha
        }
        self._request("git/refs", method="POST", data=data)

    def get_file_sha(self, branch_name: str) -> Optional[str]:
        try:
            res = self._request(f"contents/{self.target_file}?ref={branch_name}")
            return res.get("sha")
        except ValueError as e:
            if "404" in str(e) or "Not Found" in str(e):
                return None
            raise

    def commit_file(self, content: str, branch_name: str, file_sha: Optional[str] = None) -> None:
        encoded_content = base64.b64encode(content.encode("utf-8")).decode("utf-8")
        data = {
            "message": "remediation: sync LLM prompt spec with API schema changes",
            "content": encoded_content,
            "branch": branch_name
        }
        if file_sha:
            data["sha"] = file_sha
        self._request(f"contents/{self.target_file}", method="PUT", data=data)

    def create_pull_request(self, branch_name: str, verification_status: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        body = (
            "This PR was automatically generated by LOD (LLM-Optimized Documentation) to resolve API schema drift.\n\n"
            "### Changes\n"
            f"- Re-compiled LLM-Optimized Markdown (LOM) prompt definition for `{self.target_file}` using the latest schema definitions."
        )
        if verification_status:
            status_symbol = "✅ **Verification Succeeded**" if verification_status["success"] else "⚠️ **Verification Failed**"
            body += (
                f"\n\n### Verification Status\n"
                f"{status_symbol}\n"
                f"- **Command**: `{verification_status['cmd']}`\n"
                f"- **Exit Code**: `{verification_status['returncode']}`\n\n"
                f"<details>\n"
                f"<summary>View Verification Logs</summary>\n\n"
                f"```\n"
                f"{verification_status['logs']}\n"
                f"```\n"
                f"</details>"
            )
        data = {
            "title": "remediation: sync LLM prompt spec with API schema changes",
            "head": branch_name,
            "base": self.base_branch,
            "body": body
        }
        return self._request("pulls", method="POST", data=data)

    def remediate(
        self,
        new_schema: Dict[str, Any],
        model: Optional[str] = None,
        verify_cmd: Optional[str] = None,
        allow_failed_verification: bool = False
    ) -> Dict[str, Any]:
        # Compile LOM content from the new schema
        converter = LLMOpenAPIConverter(new_schema, model=model)
        lom_content = converter.convert()

        verification_status = None
        if verify_cmd:
            original_exists = os.path.exists(self.target_file)
            original_content = None
            if original_exists:
                with open(self.target_file, "r", encoding="utf-8") as f:
                    original_content = f.read()

            parent_dir = os.path.dirname(self.target_file)
            created_parent = False
            if parent_dir and not os.path.exists(parent_dir):
                os.makedirs(parent_dir, exist_ok=True)
                created_parent = True

            try:
                with open(self.target_file, "w", encoding="utf-8") as f:
                    f.write(lom_content)

                result = subprocess.run(
                    verify_cmd,
                    shell=True,
                    capture_output=True,
                    text=True
                )
                logs = f"--- stdout ---\n{result.stdout}\n--- stderr ---\n{result.stderr}"
                verification_status = {
                    "success": result.returncode == 0,
                    "returncode": result.returncode,
                    "logs": logs,
                    "cmd": verify_cmd
                }
            finally:
                if original_exists:
                    with open(self.target_file, "w", encoding="utf-8") as f:
                        f.write(original_content)
                else:
                    if os.path.exists(self.target_file):
                        os.remove(self.target_file)
                    if created_parent and os.path.exists(parent_dir) and not os.listdir(parent_dir):
                        os.rmdir(parent_dir)

            if not verification_status["success"] and not allow_failed_verification:
                raise ValueError(
                    f"Verification failed with exit code {verification_status['returncode']}.\n"
                    f"Logs:\n{verification_status['logs']}"
                )

        # Get base reference SHA
        base_sha = self.get_base_sha()

        # Create branch
        timestamp = int(time.time())
        branch_name = f"lod-remediation-{timestamp}"
        self.create_branch(branch_name, base_sha)

        # Retrieve file SHA if it exists
        file_sha = self.get_file_sha(branch_name)

        # Push file commit
        self.commit_file(lom_content, branch_name, file_sha)

        # Open Pull Request
        pr_info = self.create_pull_request(branch_name, verification_status=verification_status)

        return {
            "branch": branch_name,
            "pr_url": pr_info.get("html_url"),
            "pr_number": pr_info.get("number")
        }
